# =========================================================================
# database connection settings
# =========================================================================
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gsol_app_db
    username: apluser
    password: apluser
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
# =========================================================================
# logging config
# =========================================================================
logging:
  level:
    root: INFO
    org:
      springframework.web: DEBUG
      hibernate:
        SQL: debug
        type:
          EnumType: trace
          descriptor:
            sql:
              BasicBinder: trace
  file: application.log
  # Logging pattern for file
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
