# =========================================================================
# database connection settings
# =========================================================================
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gsol_app_db
    username: apluser
    password: apluser
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
# =========================================================================
# logging sql query
# =========================================================================
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          EnumType: trace
          descriptor:
            sql:
              BasicBinder: trace
              